version: "2"
linters:
  default: standard
  enable:
    - forbidigo
    - errorlint
    - gocritic
    - misspell
    - unconvert
  settings:
    forbidigo:
      analyze-types: true
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - cluster-plex
