// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: remux.proto

package remuxpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Job struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Input           string                 `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	StartMs         int64                  `protobuf:"varint,2,opt,name=start_ms,json=startMs,proto3" json:"start_ms,omitempty"`
	SkipToSegment   int32                  `protobuf:"varint,3,opt,name=skip_to_segment,json=skipToSegment,proto3" json:"skip_to_segment,omitempty"`
	SegmentMs       int64                  `protobuf:"varint,4,opt,name=segment_ms,json=segmentMs,proto3" json:"segment_ms,omitempty"`
	VideoStream     int32                  `protobuf:"varint,5,opt,name=video_stream,json=videoStream,proto3" json:"video_stream,omitempty"`
	AudioStream     int32                  `protobuf:"varint,6,opt,name=audio_stream,json=audioStream,proto3" json:"audio_stream,omitempty"`
	AudioCopy       bool                   `protobuf:"varint,7,opt,name=audio_copy,json=audioCopy,proto3" json:"audio_copy,omitempty"`
	AudioChannels   int32                  `protobuf:"varint,8,opt,name=audio_channels,json=audioChannels,proto3" json:"audio_channels,omitempty"`
	AudioSampleRate int32                  `protobuf:"varint,9,opt,name=audio_sample_rate,json=audioSampleRate,proto3" json:"audio_sample_rate,omitempty"`
	AudioBitRate    int64                  `protobuf:"varint,10,opt,name=audio_bit_rate,json=audioBitRate,proto3" json:"audio_bit_rate,omitempty"`
	AudioLanguage   string                 `protobuf:"bytes,11,opt,name=audio_language,json=audioLanguage,proto3" json:"audio_language,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_remux_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_remux_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_remux_proto_rawDescGZIP(), []int{0}
}

func (x *Job) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *Job) GetStartMs() int64 {
	if x != nil {
		return x.StartMs
	}
	return 0
}

func (x *Job) GetSkipToSegment() int32 {
	if x != nil {
		return x.SkipToSegment
	}
	return 0
}

func (x *Job) GetSegmentMs() int64 {
	if x != nil {
		return x.SegmentMs
	}
	return 0
}

func (x *Job) GetVideoStream() int32 {
	if x != nil {
		return x.VideoStream
	}
	return 0
}

func (x *Job) GetAudioStream() int32 {
	if x != nil {
		return x.AudioStream
	}
	return 0
}

func (x *Job) GetAudioCopy() bool {
	if x != nil {
		return x.AudioCopy
	}
	return false
}

func (x *Job) GetAudioChannels() int32 {
	if x != nil {
		return x.AudioChannels
	}
	return 0
}

func (x *Job) GetAudioSampleRate() int32 {
	if x != nil {
		return x.AudioSampleRate
	}
	return 0
}

func (x *Job) GetAudioBitRate() int64 {
	if x != nil {
		return x.AudioBitRate
	}
	return 0
}

func (x *Job) GetAudioLanguage() string {
	if x != nil {
		return x.AudioLanguage
	}
	return ""
}

type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Event_File
	//	*Event_Manifest
	//	*Event_Progress
	//	*Event_Done
	Kind          isEvent_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_remux_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_remux_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_remux_proto_rawDescGZIP(), []int{1}
}

func (x *Event) GetKind() isEvent_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Event) GetFile() *File {
	if x != nil {
		if x, ok := x.Kind.(*Event_File); ok {
			return x.File
		}
	}
	return nil
}

func (x *Event) GetManifest() *Manifest {
	if x != nil {
		if x, ok := x.Kind.(*Event_Manifest); ok {
			return x.Manifest
		}
	}
	return nil
}

func (x *Event) GetProgress() *Progress {
	if x != nil {
		if x, ok := x.Kind.(*Event_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *Event) GetDone() *Done {
	if x != nil {
		if x, ok := x.Kind.(*Event_Done); ok {
			return x.Done
		}
	}
	return nil
}

type isEvent_Kind interface {
	isEvent_Kind()
}

type Event_File struct {
	File *File `protobuf:"bytes,1,opt,name=file,proto3,oneof"`
}

type Event_Manifest struct {
	Manifest *Manifest `protobuf:"bytes,2,opt,name=manifest,proto3,oneof"`
}

type Event_Progress struct {
	Progress *Progress `protobuf:"bytes,3,opt,name=progress,proto3,oneof"`
}

type Event_Done struct {
	Done *Done `protobuf:"bytes,4,opt,name=done,proto3,oneof"`
}

func (*Event_File) isEvent_Kind() {}

func (*Event_Manifest) isEvent_Kind() {}

func (*Event_Progress) isEvent_Kind() {}

func (*Event_Done) isEvent_Kind() {}

// File is a segment file to write into the session directory.
type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_remux_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_remux_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_remux_proto_rawDescGZIP(), []int{2}
}

func (x *File) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *File) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Manifest is posted to Plex once the files it lists are written.
type Manifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mpd           []byte                 `protobuf:"bytes,1,opt,name=mpd,proto3" json:"mpd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manifest) Reset() {
	*x = Manifest{}
	mi := &file_remux_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest) ProtoMessage() {}

func (x *Manifest) ProtoReflect() protoreflect.Message {
	mi := &file_remux_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifest.ProtoReflect.Descriptor instead.
func (*Manifest) Descriptor() ([]byte, []int) {
	return file_remux_proto_rawDescGZIP(), []int{3}
}

func (x *Manifest) GetMpd() []byte {
	if x != nil {
		return x.Mpd
	}
	return nil
}

// Progress is a PUT under the job's progress URL: path "" , "stream" or
// "streamDetail", query the already-encoded query string.
type Progress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Progress) Reset() {
	*x = Progress{}
	mi := &file_remux_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Progress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Progress) ProtoMessage() {}

func (x *Progress) ProtoReflect() protoreflect.Message {
	mi := &file_remux_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Progress.ProtoReflect.Descriptor instead.
func (*Progress) Descriptor() ([]byte, []int) {
	return file_remux_proto_rawDescGZIP(), []int{4}
}

func (x *Progress) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Progress) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

// Done ends the stream; an empty error is success.
type Done struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Done) Reset() {
	*x = Done{}
	mi := &file_remux_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Done) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Done) ProtoMessage() {}

func (x *Done) ProtoReflect() protoreflect.Message {
	mi := &file_remux_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Done.ProtoReflect.Descriptor instead.
func (*Done) Descriptor() ([]byte, []int) {
	return file_remux_proto_rawDescGZIP(), []int{5}
}

func (x *Done) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_remux_proto protoreflect.FileDescriptor

const file_remux_proto_rawDesc = "" +
	"\n" +
	"\vremux.proto\x12\x05remux\"\x82\x03\n" +
	"\x03Job\x12\x14\n" +
	"\x05input\x18\x01 \x01(\tR\x05input\x12\x19\n" +
	"\bstart_ms\x18\x02 \x01(\x03R\astartMs\x12&\n" +
	"\x0fskip_to_segment\x18\x03 \x01(\x05R\rskipToSegment\x12\x1d\n" +
	"\n" +
	"segment_ms\x18\x04 \x01(\x03R\tsegmentMs\x12!\n" +
	"\fvideo_stream\x18\x05 \x01(\x05R\vvideoStream\x12!\n" +
	"\faudio_stream\x18\x06 \x01(\x05R\vaudioStream\x12\x1d\n" +
	"\n" +
	"audio_copy\x18\a \x01(\bR\taudioCopy\x12%\n" +
	"\x0eaudio_channels\x18\b \x01(\x05R\raudioChannels\x12*\n" +
	"\x11audio_sample_rate\x18\t \x01(\x05R\x0faudioSampleRate\x12$\n" +
	"\x0eaudio_bit_rate\x18\n" +
	" \x01(\x03R\faudioBitRate\x12%\n" +
	"\x0eaudio_language\x18\v \x01(\tR\raudioLanguage\"\xb3\x01\n" +
	"\x05Event\x12!\n" +
	"\x04file\x18\x01 \x01(\v2\v.remux.FileH\x00R\x04file\x12-\n" +
	"\bmanifest\x18\x02 \x01(\v2\x0f.remux.ManifestH\x00R\bmanifest\x12-\n" +
	"\bprogress\x18\x03 \x01(\v2\x0f.remux.ProgressH\x00R\bprogress\x12!\n" +
	"\x04done\x18\x04 \x01(\v2\v.remux.DoneH\x00R\x04doneB\x06\n" +
	"\x04kind\".\n" +
	"\x04File\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\x1c\n" +
	"\bManifest\x12\x10\n" +
	"\x03mpd\x18\x01 \x01(\fR\x03mpd\"4\n" +
	"\bProgress\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\"\x1c\n" +
	"\x04Done\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error2,\n" +
	"\x05Remux\x12#\n" +
	"\x05Remux\x12\n" +
	".remux.Job\x1a\f.remux.Event0\x01B/Z-github.com/mediactl/clusterplex/proto/remuxpbb\x06proto3"

var (
	file_remux_proto_rawDescOnce sync.Once
	file_remux_proto_rawDescData []byte
)

func file_remux_proto_rawDescGZIP() []byte {
	file_remux_proto_rawDescOnce.Do(func() {
		file_remux_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_remux_proto_rawDesc), len(file_remux_proto_rawDesc)))
	})
	return file_remux_proto_rawDescData
}

var file_remux_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_remux_proto_goTypes = []any{
	(*Job)(nil),      // 0: remux.Job
	(*Event)(nil),    // 1: remux.Event
	(*File)(nil),     // 2: remux.File
	(*Manifest)(nil), // 3: remux.Manifest
	(*Progress)(nil), // 4: remux.Progress
	(*Done)(nil),     // 5: remux.Done
}
var file_remux_proto_depIdxs = []int32{
	2, // 0: remux.Event.file:type_name -> remux.File
	3, // 1: remux.Event.manifest:type_name -> remux.Manifest
	4, // 2: remux.Event.progress:type_name -> remux.Progress
	5, // 3: remux.Event.done:type_name -> remux.Done
	0, // 4: remux.Remux.Remux:input_type -> remux.Job
	1, // 5: remux.Remux.Remux:output_type -> remux.Event
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_remux_proto_init() }
func file_remux_proto_init() {
	if File_remux_proto != nil {
		return
	}
	file_remux_proto_msgTypes[1].OneofWrappers = []any{
		(*Event_File)(nil),
		(*Event_Manifest)(nil),
		(*Event_Progress)(nil),
		(*Event_Done)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_remux_proto_rawDesc), len(file_remux_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_remux_proto_goTypes,
		DependencyIndexes: file_remux_proto_depIdxs,
		MessageInfos:      file_remux_proto_msgTypes,
	}.Build()
	File_remux_proto = out.File
	file_remux_proto_goTypes = nil
	file_remux_proto_depIdxs = nil
}
