// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: remux.proto

package remuxpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Remux_Remux_FullMethodName = "/remux.Remux/Remux"
)

// RemuxClient is the client API for Remux service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Remux runs one browser remux on a remux worker. The worker never talks to
// Plex: segments, manifests and progress all come back on the stream, and
// the serving pod's manager delivers them.
type RemuxClient interface {
	Remux(ctx context.Context, in *Job, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
}

type remuxClient struct {
	cc grpc.ClientConnInterface
}

func NewRemuxClient(cc grpc.ClientConnInterface) RemuxClient {
	return &remuxClient{cc}
}

func (c *remuxClient) Remux(ctx context.Context, in *Job, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Remux_ServiceDesc.Streams[0], Remux_Remux_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Job, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Remux_RemuxClient = grpc.ServerStreamingClient[Event]

// RemuxServer is the server API for Remux service.
// All implementations must embed UnimplementedRemuxServer
// for forward compatibility.
//
// Remux runs one browser remux on a remux worker. The worker never talks to
// Plex: segments, manifests and progress all come back on the stream, and
// the serving pod's manager delivers them.
type RemuxServer interface {
	Remux(*Job, grpc.ServerStreamingServer[Event]) error
	mustEmbedUnimplementedRemuxServer()
}

// UnimplementedRemuxServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRemuxServer struct{}

func (UnimplementedRemuxServer) Remux(*Job, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method Remux not implemented")
}
func (UnimplementedRemuxServer) mustEmbedUnimplementedRemuxServer() {}
func (UnimplementedRemuxServer) testEmbeddedByValue()               {}

// UnsafeRemuxServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RemuxServer will
// result in compilation errors.
type UnsafeRemuxServer interface {
	mustEmbedUnimplementedRemuxServer()
}

func RegisterRemuxServer(s grpc.ServiceRegistrar, srv RemuxServer) {
	// If the following call panics, it indicates UnimplementedRemuxServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Remux_ServiceDesc, srv)
}

func _Remux_Remux_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Job)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RemuxServer).Remux(m, &grpc.GenericServerStream[Job, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Remux_RemuxServer = grpc.ServerStreamingServer[Event]

// Remux_ServiceDesc is the grpc.ServiceDesc for Remux service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Remux_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "remux.Remux",
	HandlerType: (*RemuxServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Remux",
			Handler:       _Remux_Remux_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "remux.proto",
}
