apiVersion: v1
kind: ServiceAccount
metadata:
  name: clusterplex-sa
  namespace: media
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: clusterplex-role
  namespace: media
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "watch", "list", "create", "update", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: clusterplex-binding
  namespace: media
subjects:
  - kind: ServiceAccount
    name: clusterplex-sa
roleRef:
  kind: Role
  name: clusterplex-role
  apiGroup: rbac.authorization.k8s.io
